### ISSUE TITLE
Intermittent operation

### ISSUE THREAD

**Issue by ttk2** [Celdecea/MusterCull#2]
I have had issues running previous versions of MusterCull because they seemed to generate concurrent modification exceptions with Spigot. Since Spigot makes a ton of changes to how mobs operate its really no surprise but it does make MusterCull unusable on servers running Spigot. 

Right now I need something to limit Spawners, this morning I logged in and the tick as 4, I run a single command to clear all monsters on the map, instantly 20. We have too many people grinding and gathering up useless mobs. But since it seems that it takes quite a few minutes for the number of mobs to build up again I think it would be best if MusterCull simply operated on a timer, removing excess mobs every 30 minutes, 10 minutes, or even time measured in ticks. 

Becuase it runs out of sync it should not try and access the thread at the same time as Spigot and prevent crashing while solving the problem.

**Comment by Celdecea** [comment]
I will fix the concurrent modification exception. The feature to kill mobs on a timer is already implemented in MusterCull but apparently a bit buggy, so let me look into that and I'll get you an updated config.yml. The generously high values of 100 and 150 we were using probably were not a good idea; perhaps 10 and 15 would be better (you've heard of the quad spider spawner somebody just found right?).

I'm also noticing that mobs remain near my spawner long after I log out. I'd think if the chunk was staying loaded the melons would grow nearby but those don't, yet after several hours offline I still have a group of skeletons sitting in the collection area when I log in. I could add a simple unload listener that checks for mobs but if this is already being done there is another problem which may need to be looked in to.

Finally I have some uncommitted changes which look like some sort of command to tell you how many mobs/entities are circling around a given player including some top 5 players thing. I'll have to get that pushed soon; sorry about the delay on it.

**Comment by Celdecea** [comment]
Closed as resolved unless something else comes up.
