### ISSUE TITLE
Admin friendliness

### ISSUE THREAD

**Issue by riddle** [Celdecea/MusterCull#3]
Is there any repository where I could find compiled versions of the plugin? I’m not that advanced when it comes to Java and Eclipse and to be honest, making a plugin out of source files is beyond me. I found v1.2 (https://github.com/Celdecea/MusterCull/downloads) but it’s from 2 months ago while the most recent change in your repo is from 6 days ago. 

Could you help me out?

**Comment by Celdecea** [comment]
My apologies. I am not at a place where I can upload it at this time but will be in about 27 hours. The current version will be in the downloads then.

I will endeavor to make sure I remember this from now on.

**Comment by ttk2** [comment]
I always liked Erocs policy of just linking to a compiled .jar download in
every pull request.

**Comment by Celdecea** [comment]
[Here is the download](http://www.mediafire.com/file/g5l8gxt6e90a7ks/MusterCull-1.3.jar)

I will make sure to include a jar link with pushes.

**Comment by riddle** [comment]
Thank you so much!
