### ISSUE TITLE
Damaging already established animal farms

### ISSUE THREAD

**Issue by riddle** [Celdecea/MusterCull#5]
I’m wondering about this passage from readme:

> Keep damage_count low (1 or 2 and no more than 5).

I tested this on a pen of 200 cows and they were damaged so slow and I could easily see the queue… so for all my players and all their animal farms, it would take forever to clean up. Is there anything you could suggest?

**Comment by Celdecea** [comment]
I would use a higher damage (not damage_count) until the farms are under
control. The range is a very important setting, but numbers greater than 30
have less effect. I have found between 5 and 20 giving the most dramatic
changes.

Increasing damage_count only increases the number of mobs hit during the
tick cycle, so if your performance is well and you benefit from the
aggressiveness go ahead and experiment with higher numbers. The method
which does the culling blocks a bit though, so you may see bizarre pauses.
Your mileage may vary.

If you know where an offending farm is you can do a little manual cleanup
too using the /muster command as well.

**Comment by riddle** [comment]
Alright. Is range a 5×5 area or a circle with r=5?

**Comment by Celdecea** [comment]
Range uses an axis-aligned bounding box, so range 5 would be about 10x10x10
cube around the entity.
