### ISSUE TITLE
Compatibility with bukkit 1.4.6 dev?

### ISSUE THREAD

**Issue by riddle** [Celdecea/MusterCull#7]
Hello, recently all advanced plugins using private APIs broke down when Bukkit was updated to 1.4.5 (and later to 1.4.6). Is MusterCull 1.3.1 compatible with the newest release?

**Comment by Celdecea** [comment]
Surprisingly MusterCull was not broke during the 1.4.5 update. I believe
plugins accessing certain block data were affected but that isn't necessary
for this plugin to work.

I am doing 1.4.6 testing this week and will be able to answer your question
soon.

**Comment by Celdecea** [comment]
MusterCull is compatible with 1.4.6 R0.3.
