### ISSUE TITLE
 Plugin damages friendly mobs without being told to.

### ISSUE THREAD

**Issue by dpedu** [Celdecea/MusterCull#9]
Hi,

I'm using the following config options: http://pastebin.com/XRKEuLJ6

I have observed villagers and cows being automatically killed. Disabling the plugin stops this. 

Also, setting damage to zero and damage chance to zero does not stop this behavior.

**Comment by Celdecea** [comment]
Hello, thank you for reporting this. I believe I see a temporary solution for you.

There is a new laborer thanks to Felzix which works on a different set of rules, specifically a hard mob cap. I apologize if this hasn't been clearly documented yet, and I have no excuse for not doing so.

Try adding the following global configuration lines:

mob_max_mob: 10000
mob_player_multiplier: 1

The max_mob is obvious, but the player_multiplier reduces it by n*online_player_count. These two figures should be liberal enough for almost all servers.

If the issue still persists then let me know as it may indicate a more serious issue.

**Comment by ttk2** [comment]
Is this live in the version I am running?

**Comment by Celdecea** [comment]
ttk2: yours would've had the configuration settings I believe. If you send me your config.yml separately I can confirm it for you, or just check for those two lines.

That is if my assumption is correct; my test environment for MusterCull is 25 hours away.

**Comment by dpedu** [comment]
The version the bug above I posted was compiled from the source on this Github yesterday. However, it seems adding the lines to my config suggested by Celdecea solved the issue. Thanks for the help! :-)
